const data = { 
  places: [
    {
      id: 1,
      name: "Atlas Pizza",
      address: "6529 SE Foster Rd, Portland, OR 97206",
      neighborhood: "SE",
      phone: "503-232-3004",
      website: "http://atlaspizzapdx.com",
      hours: {
        "Monday": "12:00 pm - 11:00 pm",
        "Tuesday": "12:00 pm - 11:00 pm",
        "Wednesday": "12:00 pm - 11:00 pm",
        "Thursday": "12:00 pm - 11:00 pm",
        "Friday": "12:00 pm - 12:00 am",
        "Saturday": "12:00 pm - 12:00 am",
        "Sunday": "12:00 pm - 11:00 pm",
      },
      hours2: [
        {
          "dayOfWeek": "Monday",
          "opens": "12:00 pm",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Tuesday",
          "opens": "12:00 pm",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Wednesday",
          "opens": "12:00 pm",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Thursday",
          "opens": "12:00 pm",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Friday",
          "opens": "12:00 pm",
          "closes": "12:00 am",
        },
        {
          "dayOfWeek": "Saturday",
          "opens": "12:00 pm",
          "closes": "12:00 am",
        },
        {
          "dayOfWeek": "Sunday",
          "opens": "12:00 pm",
          "closes": "11:00 pm",
        },
      ],
      date_added: "2019-06-13",
      category: "restaurants",
      descriptors: [ "pizza", "arcade", "beer" ],
      features: { 
        "toys": true, 
        "play area": true, 
        "arcade": true,
        "quick service": true,
        "all ages": true,
        "comfortable seating": true,
        "friendly staff": true,
        "kids menu": false,
        "highchairs/boosters": false,
        "changing station": false,
        "flexible": true,
        "patio/sidewalk": true,
      },
      images: [
        {
          id: 1,
          src: 'https://lh3.googleusercontent.com/b4_IwDpum2tACP0SzV50swe62O0D81hWlaMD7yYdQtMIhHq1eEvlivffLVr7UAE8NggaPSZDlkD1Hz1GyFt_TTkjbZgfJmDXL4H_vbWajPNkeZ4zpatDAl-phv_yatVsKjQoC-8xWzc=w2400',
          title: `Atlas Pizza's 'Jalapeno Popper' pie`,
          user_id: "",
        },
        {
          id: 2,
          src: 'https://lh3.googleusercontent.com/wg6hQ73LsdrlPLngxGMtJK5TV750qXjUVI9i3hEzbTi4CiOv0sP8EWzAsDWtiKljlnbT31CswgaExeOphfOScxA5rBiK9bhmFvrQgaD97dTMy_c_4OiPZMafO0eVfwQRkj3LJEHsFo8=w2400',
          title: 'A rainbow over Foster Blvd',
          user_id: "",
        },
      ],
      number_of_reviews: 2,
      average_review_rating: 4.5,
    },
    {
      id: 2,
      name: "Grand Central Bakery",
      address: "4412 SE Woodstock Blvd, Portland, OR 97206",
      neighborhood: "SE",
      phone: "503-953-1250",
      website: "https://www.grandcentralbakery.com/find-us/portland/woodstock/",
      hours: {
        "Monday": "7:00 am - 6:00 pm",
        "Tuesday": "7:00 am - 6:00 pm",
        "Wednesday": "7:00 am - 6:00 pm",
        "Thursday": "7:00 am - 6:00 pm",
        "Friday": "7:00 am - 6:00 pm",
        "Saturday": "7:00 am - 6:00 pm",
        "Sunday": "7:00 am - 6:00 pm",
      },
      hours2: [
        {
          "dayOfWeek": "Monday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Tuesday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Wednesday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Thursday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Friday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Saturday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Sunday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
      ],
      date_added: "2019-06-13",
      category: "restaurants",
      descriptors: [ "cafe", "bakery", "pastries", ],
      features: { 
        "toys": false, 
        "play area": false, 
        "arcade": false,
        "quick service": true,
        "all ages": true,
        "comfortable seating": true,
        "friendly staff": true,
        "kids menu": false,
        "highchairs/boosters": true,
        "changing station": true,
        "flexible": true,
        "patio/sidewalk": true,
      },
      images: [
        {
          id: 1,
          src: 'https://lh3.googleusercontent.com/56bcsrMIK1Xbg28JdLI3glyg1LxzfymBv-pJ9dPGnIl7oHXJpPhogQltWQ2p3I8rUDIVypaNlaQ5iCo0wOSyo1LkpMoDFGFZg2dGB-s-sUxTgdVDrUX6bKxPR3XMHuqKX4Jd2FFJW8w=w2400',
          title: 'Fresh loaf!',
          user_id: "",
        },
        {
          id: 2,
          src: 'https://lh3.googleusercontent.com/XRryFmt3JSXIJIT1zbf62mPE5r7yGe4k_f4-SGexchJ-RYsPfQd5daowbB1KCGUlwhYJIMtxnT5cnO-T6mmN0KBaEIeaI98sj1qx_wJJ_-YKKy1nSjp8-Idhn4LRA6h2xcJ1984utAg=w2400',
          title: 'A box of assorted pastries',
          user_id: "",
        },
      ],
      number_of_reviews: 1,
      average_review_rating: 4,
    },
    {
      id: 3,
      name: "Hopworks Urban Brewery: Powell",
      address: "2944 SE Powell Blvd, Portland, OR 97202",
      neighborhood: "SE",
      phone: "503-232-4677",
      website: "https://hopworksbeer.com/eat/powell/",
      hours: {
        "Monday": "11:00 am - 11:00 pm",
        "Tuesday": "11:00 am - 11:00 pm",
        "Wednesday": "11:00 am - 11:00 pm",
        "Thursday": "11:00 am - 11:00 pm",
        "Friday": "11:00 am - 12:00 am",
        "Saturday": "11:00 am - 12:00 am",
        "Sunday": "11:00 am - 11:00 pm",
      },
      hours2: [
        {
          "dayOfWeek": "Monday",
          "opens": "11:00 am",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Tuesday",
          "opens": "11:00 am",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Wednesday",
          "opens": "11:00 am",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Thursday",
          "opens": "11:00 am",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Friday",
          "opens": "11:00 am",
          "closes": "12:00 am",
        },
        {
          "dayOfWeek": "Saturday",
          "opens": "11:00 am",
          "closes": "12:00 am",
        },
        {
          "dayOfWeek": "Sunday",
          "opens": "11:00 am",
          "closes": "11:00 pm",
        },
      ],
      date_added: "2019-06-13",
      category: "restaurants",
      descriptors: [ "pizza", "burgers", "beer",],
      features: { 
        "toys": true, 
        "play area": true, 
        "arcade": false,
        "quick service": true,
        "all ages": true,
        "comfortable seating": true,
        "friendly staff": true,
        "kids menu": true,
        "highchairs/boosters": true,
        "changing station": true,
        "flexible": true,
        "patio/sidewalk": true,
      },
      images: [],
      number_of_reviews: 1,
      average_review_rating: "4.4",
    },
  ],
  users: [
    { 
      id: 1,
      full_name: "Charlie Kelly",
      email: "charlie@alwayssunny.com",
      password: "Charlie100%",
      display_name: "Charlie",
      date_created: "2019-06-13",
    },
    { 
      id: 2,
      full_name: "Ronald McDonald",
      email: "mac@alwayssunny.com",
      password: "Mac100%!",
      display_name: "Mac",
      date_created: "2019-06-13",
    },
    { 
      id: 3,
      full_name: "Deandra Reynolds",
      email: "sweetdee@alwayssunny.com",
      password: "SweetDee100%",
      display_name: "Sweet Dee",
      date_created: "2019-06-13",
    },
    { 
      id: 4,
      full_name: "Dennis Reynolds",
      email: "dennis@alwayssunny.com",
      password: "Dennis100%",
      display_name: "Dennis",
      date_created: "2019-06-13",
    },
  ],
  reviews: [
  { 
    id: 1,
    star_rating: 5,
    text: "Awesome Big Trouble in Little China poster!",
    date_created: "2019-06-13",
    place_id: "1",
    user_id: "2",
    images: [],
  },
  { 
    id: 2,
    star_rating: 4,
    text: "Very easy place to take kids of all ages. Nice toy area with a great variety of toys!",
    date_created: "2019-06-13",
    place_id: "1",
    user_id: "1",
    images: [],
  },
  { 
    id: 3,
    star_rating: 4,
    text: "Sidewalk picnic tables are a bonus. Kids can explore the other shops on the street and play with dogs.",
    date_created: "2019-06-13",
    place_id: "2",
    user_id: "3",
    images: [],
  },
  ]
};

export default data;